---
title: "R Notebook"
NIM: 19523200, 19523221
Nama: Muhammad Imam Fauzi, Rafi Rahmat Irwan
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)    #datamanipulation  
library(cluster)      #clusteringalgorithm
library(factoextra)   #clusteringalgorithm&visualization
```
```{r}
data = read.delim("Wholesale customers data.csv", sep = ",")
summary(data)
summary(is.na(data)) #cek data kosong
```
```{r}
data.baru <- data[, 2:5]
data.class <- data[, "Channel"]
set.seed(1432)
result <- kmeans(data.baru, 3)
result
```

```{r}
par(mfrow=c(2,2), mar=c(5,4,2,2))
plot(data.baru[, c(1,2)], col=result$cluster)
plot(data.baru[, c(1,2)], col=data.class)
plot(data.baru[, c(3,4)], col=result$cluster)
plot(data.baru[, c(3,4)], col=data.class)
```

```{r}
data.baru$cluster <- factor(result$cluster)
centers <- as.data.frame(result$centers)
library(ggplot2)
ggplot() +
  geom_point(data=data.baru, aes(x=Milk, y=Grocery, color=cluster)) +
  geom_point(data=centers, aes(x=Milk, y=Grocery, color="Center"),
             size=52, alpha=.3, show.legend = FALSE)
```



